name: Odoo Module Test

on:
  push:
    branches:
      - 17.0
  pull_request:
    branches:
      - 17.0

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential python3-dev libxml2-dev libxslt1-dev zlib1g-dev libldap2-dev libsasl2-dev libjpeg-dev libpq-dev
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Odoo
      run: |
        git clone https://github.com/odoo/odoo.git --depth=1 --branch 16.0
        cd odoo
        pip install -r requirements.txt
        cp odoo/tools/config.py .

    - name: Create Odoo Config File
      run: |
        echo "
        [options]
        addons_path = addons,custom_addons
        db_host = localhost
        db_port = 5432
        db_user = odoo
        db_password = odoo
        log_level = info
        " > odoo.conf

    - name: Install Odoo & Modules
      run: |
        cd odoo
        ./odoo-bin -c ../odoo.conf --init=base
        ./odoo-bin -c ../odoo.conf -d test_db --init=server_management --stop-after-init

    - name: Run Tests
      run: |
        cd odoo
        ./odoo-bin -c ../odoo.conf -d test_db --test-enable --stop-after-init --log-level=debug
